# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTEST2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tEST2(self):
    # Test name: TEST2
    # Step # | name | target | value | comment
    # 1 | open | http://suninjuly.github.io/registration1.html |  | 
    self.driver.get("http://suninjuly.github.io/registration1.html")
    # 2 | setWindowSize | 969x1020 |  | 
    self.driver.set_window_size(969, 1020)
    # 3 | click | css=.first_block > .first_class > .form-control |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".first_block > .first_class > .form-control").click()
    # 4 | type | css=.first_block > .first_class > .form-control | ivan | 
    self.driver.find_element(By.CSS_SELECTOR, ".first_block > .first_class > .form-control").send_keys("ivan")
    # 5 | click | css=.third |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".third").click()
    # 6 | click | css=.first_block > .second_class > .form-control |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".first_block > .second_class > .form-control").click()
    # 7 | type | css=.first_block > .second_class > .form-control | petrov | 
    self.driver.find_element(By.CSS_SELECTOR, ".first_block > .second_class > .form-control").send_keys("petrov")
    # 8 | click | css=form |  | 
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    # 9 | click | css=.third |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".third").click()
    # 10 | type | css=.third | test@test.com | 
    self.driver.find_element(By.CSS_SELECTOR, ".third").send_keys("test@test.com")
    # 11 | click | css=.btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 12 | click | css=.bg-light |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".bg-light").click()
  
