# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTEST2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tEST2(self):
    # Test name: TEST2
    # Step # | name | target | value | comment
    # 1 | open | http://suninjuly.github.io/find_xpath_form |  | 
    self.driver.get("http://suninjuly.github.io/find_xpath_form")
    # 2 | setWindowSize | 1692x936 |  | 
    self.driver.set_window_size(1692, 936)
    # 3 | click | xpath=//input[@name='first_name'] |  | 
    self.driver.find_element(By.XPATH, "//input[@name=\'first_name\']").click()
    # 4 | type | xpath=//input[@name='first_name'] | ivan | 
    self.driver.find_element(By.XPATH, "//input[@name=\'first_name\']").send_keys("ivan")
    # 5 | type | xpath=//input[@name='last_name'] | ptrov | 
    self.driver.find_element(By.XPATH, "//input[@name=\'last_name\']").send_keys("ptrov")
    # 6 | type | xpath=//input[@name='firstname'] | rus | 
    self.driver.find_element(By.XPATH, "//input[@name=\'firstname\']").send_keys("rus")
    # 7 | type | xpath=//input[@id='country'] | ris | 
    self.driver.find_element(By.XPATH, "//input[@id=\'country\']").send_keys("ris")
    # 8 | click | xpath=//input[@id='country'] |  | 
    self.driver.find_element(By.XPATH, "//input[@id=\'country\']").click()
  
