# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTEST2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tEST2(self):
    self.driver.get("http://suninjuly.github.io/registration1.html")
    self.driver.set_window_size(969, 1020)
    self.driver.find_element(By.CSS_SELECTOR, ".first_block > .first_class > .form-control").send_keys("ivan")
    self.driver.find_element(By.CSS_SELECTOR, ".first_block > .second_class > .form-control").send_keys("petrov")
    self.driver.find_element(By.CSS_SELECTOR, ".third").send_keys("test@test.com")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-light").click()
  
